require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions:
    rubocop-rake: true
    rubocop-rails: true
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# TODO: remove this
Rails/I18nLocaleTexts:
  Enabled: false